### ISSUE TITLE
Consolidate symbolic functions?

### ISSUE THREAD

**Issue by SamDuffield** [CQCL/pytket-qujax#37]
Current API is to use `tk_to_qujax(circuit)` or `tk_to_qujax_symbolic(circuit, symbol_map)` for more sophisticated parameterisations

Possibly we should consider merging this to `tk_to_qujax(circuit)` or `tk_to_qujax(circuit, symbol_map)` interface, where the symbolic interpretation is implied by the `symbol_map` argument.

Major stumbling block to this is that currently, `tk_to_qujax(circuit)` and `tk_to_qujax_symbolic(circuit, symbol_map=None)` behave differently. Notably, `tk_to_qujax_symbolic(circuit, symbol_map=None)` looks for parameterised gates in `circuit.free_symbols()` and `tk_to_qujax(circuit)` in `qujax.gates`

**Comment by SamDuffield** [comment]
possible solution is to have the following API

`tk_to_qujax(circuit: Circuit, symbol_map: Union[bool, dict] = False)`

where

- `symbol_map = False` does the usual looking up of parameterised gates in `qujax.gates`
- `symbol_map = True` looks for parameterised gates in `circuit.free_symbols()`
- `symbol_map = input_dict` uses `input_dict`

**Comment by kplekhanov** [comment]
tried to do it here https://github.com/CQCL/pytket-qujax/pull/38

**Comment by SamDuffield** [comment]
Consolidated in #43
